# https://github.com/jekyll/minima
remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme
title: s3d.rs
minima:
  skin: dark
  social_links:
    github: s3d-rs
header_pages:
  - docs/commands.md
  - docs/config.md
  - docs/examples.md
